//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Price { get; set; }
        public string Description { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> QuantityNeeded { get; set; }
        public string Image { get; set; }
        public int AreaID { get; set; }
        public int ProductTypeID { get; set; }
    
        public virtual ProductType ProductType { get; set; }
        public virtual Area Area { get; set; }
    }
}
